### ISSUE TITLE
Bad version string

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/geoviews-feedstock#22]
The latest conda package reports:

```
python -c "import geoviews; print(geoviews.__version__)"                           
0.0.0+g33876c88-gitarchive
```

that probably happens with older versions too. @philippjfr I see geoviews does not use setuptookls_scm but instead code its own solution in https://github.com/holoviz/geoviews/blob/v1.9.1/setup.py#L17-L32. The GH tarball won't have the tag information and we should probably try to use that `.version` file.

Thanks @rsignell-usgs for reporting this one.

**Comment by philippjfr** [comment]
Thanks, that's on me not paying close attention. The recipe definitely should not point at the GH tarball since that does not include the .version file. I'll try to get a new build out which uses the PyPI release.

**Comment by rsignell-usgs** [comment]
@philippjfr or @ocefpaf, just to help me understand, how is @ahuang11 [getting the right output from 1.9.1](https://discourse.holoviz.org/t/strange-hover-values-for-lon-lat-in-pandas-data/2729/4) when he does `gv.__version__`?

**Comment by philippjfr** [comment]
Suspect he installed it from the `pyviz` channel, not `conda-forge`.

**Comment by ocefpaf** [comment]
> Suspect he installed it from the `pyviz` channel, not `conda-forge`.

Or PyPI wheels. Anyway, those pkgs **are** the same version.
