### ISSUE TITLE
Remove `datashader` from requirements and rebuild to get support for Python=3.11

### ISSUE THREAD

**Issue by valeriupredoi** [conda-forge/geoviews-feedstock#30]
Hey guys, @robertjwilson and myself are discussing allowing support for python=3.11 for `nctookits` in https://github.com/conda-forge/nctoolkit-feedstock/issues/58 and we came along here - `geoviews` is currently limited to not supporting `python=3.11` unless if it's very old (v1.5) since `datashader` needs `numba` that in turn doesn't support 3.11 - as it is nicely mentioned in geoviews' [setup.py](https://github.com/holoviz/geoviews/blob/main/setup.py) - but, given that `datashader` is only a recommended dependency, and used only for running Jupyter notebooks (as far as I could see), would it be an option to remove it from the package's requirements in the conda recipe and rebuild? That'd be good for python=3.11 support, not so good for users running those Jupyter notebooks, but alas, the PyPI package doesn't have `datashader` as a dependency. Many packages allow for recommended deps these days, but they don't explicitly list them as core deps in their conda recipes, exactly because of possible conflicts (and ease of maintaining a lighter env), so that'd not be a biggie :grin: Cheers :beer:

**Comment by hoxbro** [comment]
I think this is already available with `geoviews-core`. Same functionality but without all the dependencies.  

`geoviews-core` on conda-forge should equal the `geoviews` on PyPi.

![image](https://user-images.githubusercontent.com/19758978/222194270-e215692b-da06-4783-bd00-b40c7af9e95c.png)

**Comment by robertjwilson** [comment]
Thanks @Hoxbro. I wasn't aware of geoviews-core. Switching to that as a requirement on conda should solve the problem.

**Comment by valeriupredoi** [comment]
cheers, gents! Will close this then, if there's a need, can always reopen - good stuff! :beer:
