### ISSUE TITLE
GeoViews 1.6.x

### ISSUE THREAD

**Issue by djhoese** [conda-forge/geoviews-feedstock#6]
According to https://github.com/pyviz/geoviews/issues/264 and @philippjfr mentioned that this issue is fixed in recent versions of geoviews (1.6+). I see that 1.6.1 is available on PyPI but isn't available on conda-forge. Is there something holding this up? Is there something I can help with?

For now I'll try installing from PyPI.

**Comment by philippjfr** [comment]
I'll probably be releasing 1.6.2 today or tomorrow and bump the conda-forge recipe at the same time. If you want to stick with conda you can also install it from the pyviz conda channel for now.

**Comment by ocefpaf** [comment]
@philippjfr I update the recipe b/c anyway b/c there were other changes I wanted to implement on it. Now we have a single feedstock for `geoviews` and `geoviews-core`. I'm archiving the old `geoview-core` feedstock.
